Support "TeslaTrackMode" folder
Tesla software 2020.8.1 added Track Mode V2 for Model 3 Performance, which
can record lap videos and telemetry in a folder named "TeslaTrackMode" in
the root of the sd card. Add support for that folder.
(untested, since I do not have a Model 3 Performance)

Fixes https://github.com/marcone/teslausb/issues/447

diff --git a/setup/pi/setup-teslausb b/setup/pi/setup-teslausb
--- a/setup/pi/setup-teslausb
+++ b/setup/pi/setup-teslausb
@@ -264,6 +264,17 @@ function create_usb_drive_backing_files () {
   then
     setup_progress "Creating backing disk files."
     /tmp/create-backingfiles.sh "$camsize" "$musicsize" "$BACKINGFILES_MOUNTPOINT"
+  else
+    # mount cam image and make sure the right directories exist
+    if modprobe -r g_mass_storage && mount /mnt/cam
+    then
+      mkdir -p /mnt/cam/TeslaCam
+      mkdir -p /mnt/cam/TeslaTrackMode
+      umount /mnt/cam
+    else
+      log "STOP: Couldn't check image"
+      exit 1
+    fi
   fi
 }
 
