Fix force setting time (#181)
* Fix force setting time

With newer raspbian, the force time set won't work because it interferes with the listening port that ntpd uses. This stops ntp and starts ntp before and after the force time set

diff --git a/run/archiveloop b/run/archiveloop
--- a/run/archiveloop
+++ b/run/archiveloop
@@ -385,9 +385,17 @@ function set_time () {
     sleep 2
   done
   log "Time still not set, attempting to force it"
+  if ! systemctl stop ntp
+  then
+    log "Failed to stop ntp daemon"
+  fi
   if ! ntpd -q -x -g
   then
     log "Failed to set time"
+  fi
+  if ! systemctl start ntp
+  then
+    log "Failed to start ntp daemon"
   fi
 }
 
