Fix race condition that could cause archiveloop to exit
If the wifi connection went away between the time that archiveloop
detected that the archive was reachable, and the time that it
actually connected to the archive, the resulting failure to mount
the archive would cause archiveloop to terminate.

archiveloop now checks whether mounting succeeded, and skips the
archive step if it didn't.

diff --git a/run/archiveloop b/run/archiveloop
--- a/run/archiveloop
+++ b/run/archiveloop
@@ -263,7 +263,12 @@ function archive_clips () {
 
   disconnect_usb_drives_from_host
 
-  /root/bin/connect-archive.sh
+  if ! /root/bin/connect-archive.sh
+  then
+    log "Couldn't connect archive, skipping archive step"
+    connect_usb_drives_to_host
+    return
+  fi
 
   if archive_teslacam_clips
   then
